# Generated by Django 4.2.27 on 2026-03-03 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0007_book_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('books', models.ManyToManyField(related_name='races', to='library.book', verbose_name='کتاب ها')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('option_1', models.TextField(verbose_name='گزینه ی یک')),
                ('option_2', models.TextField(verbose_name='گزینه ی دو')),
                ('option_3', models.TextField(verbose_name='گزینه ی سه')),
                ('option_4', models.TextField(verbose_name='گزینه ی چهار')),
                ('true_option', models.CharField(choices=[('option_1', 'گزینه ی یک'), ('option_2', 'گزینه ی دو'), ('option_3', 'گزینه ی سه'), ('option_4', 'گزینه ی چهار')], max_length=200, verbose_name='گزینه ی صحیح')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.race', verbose_name='مسابقه')),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guess', models.CharField(choices=[('option_1', 'گزینه ی یک'), ('option_2', 'گزینه ی دو'), ('option_3', 'گزینه ی سه'), ('option_4', 'گزینه ی چهار')], max_length=200, verbose_name='حدس کاربر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='race.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
