# Generated by Django 4.2.27 on 2026-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='شماره ی سوال'),
            preserve_default=False,
        ),
    ]
