# Generated by Django 4.2.27 on 2026-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_question_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوال ها'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'مسابقه', 'verbose_name_plural': 'مسابقه ها'},
        ),
        migrations.AddField(
            model_name='race',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
