# Generated by Django 4.2.27 on 2026-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_alter_ask_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
    ]
