# Generated by Django 4.2.27 on 2026-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0004_race_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='user_guess',
            field=models.CharField(blank=True, choices=[('option_1', 'گزینه ی یک'), ('option_2', 'گزینه ی دو'), ('option_3', 'گزینه ی سه'), ('option_4', 'گزینه ی چهار')], max_length=200, null=True, verbose_name='حدس کاربر'),
        ),
    ]
