# Generated by Django 4.2.27 on 2026-02-12 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='تلفن همراه باید در قالب جهانی E.164 باشد (مثلاً +989123456789).', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='تلفن همراه باید در قالب جهانی E.164 باشد (مثلاً +989123456789).', regex='^\\+[1-9]\\d{1,14}$')], verbose_name='شماره موبایل'),
        ),
    ]
