# Generated by Django 4.2.27 on 2026-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='اعتبار نویسنده'),
        ),
    ]
