# Generated by Django 4.2.27 on 2026-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybook',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybook',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
