# Generated by Django 4.2.27 on 2026-03-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_buybook_complete_buybook_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buybook',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
    ]
